// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBppEEzFl8eaVWkbYk4EPcZ53lm9Khx2UI',
    appId: '1:217086603323:web:8ae9de66ea29bebbca6c1e',
    messagingSenderId: '217086603323',
    projectId: 'lab3-abf42',
    authDomain: 'lab3-abf42.firebaseapp.com',
    storageBucket: 'lab3-abf42.appspot.com',
    measurementId: 'G-0BJJF9Z6HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ35VRddLDdgEd2I7ZTqGyrgxSHxTgSdg',
    appId: '1:217086603323:android:c58ef44a62368286ca6c1e',
    messagingSenderId: '217086603323',
    projectId: 'lab3-abf42',
    storageBucket: 'lab3-abf42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJdA9PTsMbCc0LsQ1MPniwo3TkcK2Zzbg',
    appId: '1:217086603323:ios:09e8056f6ae47cb8ca6c1e',
    messagingSenderId: '217086603323',
    projectId: 'lab3-abf42',
    storageBucket: 'lab3-abf42.appspot.com',
    iosBundleId: 'com.example.lab3',
  );
}
